<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pro</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$|&lt;|case.*:</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}|&gt;|;</string>
	<key>name</key>
	<string>Prosopon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(case)\b</string>
			<key>name</key>
			<string>keyword.control.prosopon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(let|send|become)\b</string>
			<key>name</key>
			<string>keyword.operator.prosopon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.prosopon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.prosopon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.prosopon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.prosopon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>0[xX][0-9a-fA-F]+|-?[0-9]+|-?[0-9]+[eE][+-]?[0-9]+|-?[0-9]*\.[0-9]+[eE][+-]?[0-9]+|-?[0-9]+\.[0-9]*[eE][+-]?[0-9]+</string>
			<key>name</key>
			<string>constant.numerica.prosopon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.prosopon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.prosopon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self)\b</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|true|false)\b</string>
			<key>name</key>
			<string>support.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\([a-zA-Z][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.prosopon</string>
	<key>uuid</key>
	<string>0873D72C-6F83-493F-9103-8FDE8E8DD45E</string>
</dict>
</plist>
